# CI Test Variables - Mock values for syntax checking
---
# Kubernetes configuration
kubernetes_version: "1.32.0-1.1"
vip: "192.168.1.99"
pod_network_cidr: "10.244.0.0/16"
pod_services_cidr: "10.96.0.0/12"
sandbox_image: "registry.k8s.io/pause:3.10"

# Domain configuration
domain_suffixes:
  - ""
  - ".home"
  - ".local"

# HAProxy/Keepalived
keepalived_auth_pass: "mock-ci-password"

# VM configuration
vm_template_id: 9999
vm_storage: "local-lvm"
vm_bridge: "vmbr0"

# Common settings
ansible_user: "debian"
ansible_become: true

# Network settings
cluster_network: "192.168.1.0/24"

# Mock values for CI testing
proxy_env: {}
no_proxy_env: ""