---
- name: Create Proxmox VMs
  hosts: proxmox
  become: true
  gather_facts: true
  tags: [vms, proxmox]
  vars:
    vm_ids: "{{ groups['k8s'] | map('regex_replace', '^kube', '') | list }}"
  roles:
    - proxmox_vm

- name: Configure Kubernetes apt repository
  hosts: k8s
  become: true
  any_errors_fatal: true
  tags: [k8s, repo]
  roles:
    - kubernetes_repo

- name: Install Kubernetes components
  hosts: k8s
  become: true
  any_errors_fatal: true
  tags: [k8s, install]
  roles:
    - kubernetes_install

- name: Configure containerd and networking
  hosts: k8s
  become: true
  any_errors_fatal: true
  tags: [k8s, containerd, networking]
  roles:
    - containerd

- name: Initialize Kubernetes master (using first master IP for bootstrap)
  hosts: master
  become: true
  any_errors_fatal: true
  tags: [k8s, init, master]
  roles:
    - kubeadm_init

- name: Install Cilium CNI
  hosts: master
  become: true
  any_errors_fatal: true
  tags: [k8s, cni, cilium]
  roles:
    - cilium

- name: Join nodes to cluster
  hosts: k8s
  become: true
  any_errors_fatal: true
  tags: [k8s, join]
  roles:
    - kubeadm_join

- name: Configure HAProxy and Keepalived after cluster is stable
  hosts: k8s_controller
  become: true
  tags: [k8s, ha, haproxy, keepalived]
  vars:
    haproxy_all_backends: true
  roles:
    - haproxy_keepalived

- name: Update kubeconfigs to use VIP
  hosts: k8s
  become: true
  tags: [k8s, ha, vip]
  tasks:
    - name: Update kubelet.conf to use VIP
      replace:
        path: /etc/kubernetes/kubelet.conf
        regexp: 'server: https://{{ hostvars[groups["k8s_controller"][0]]["ansible_default_ipv4"]["address"] }}:6443'
        replace: 'server: https://{{ vip }}:6443'
      notify: Restart kubelet
      when: inventory_hostname in groups['k8s']

    - name: Update admin.conf to use VIP (on controllers)
      replace:
        path: /etc/kubernetes/admin.conf
        regexp: 'server: https://{{ hostvars[groups["k8s_controller"][0]]["ansible_default_ipv4"]["address"] }}:6443'
        replace: 'server: https://{{ vip }}:6443'
      when: inventory_hostname in groups['k8s_controller']

  handlers:
    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted

- name: Configure GPU nodes
  hosts: k8s_worker
  become: true
  tags: [k8s, gpu]
  roles:
    - nvidia_gpu

- name: Configure metrics server certificates
  hosts: master
  become: true
  gather_facts: true
  tags: [k8s, metrics]
  roles:
    - metrics_server
